---

- name: Check the installed version of PHP.
  shell: '{{ php_executable }} -r "echo PHP_VERSION;"'
  register: php_installed_version
  changed_when: false
  always_run: yes

- name: Disable opcache if PHP version is < 5.5.
  set_fact:
    php_opcache_enable: 0
  when: "php_installed_version.stdout.split('.')[0] == '5' and php_installed_version.stdout.split('.')[1] < '5'"
