---
- name: Ensure PHP packages are installed (RedHat).
  yum:
    name: "{{ item }}"
    state: installed
    enablerepo: "{{ php_enablerepo }}"
  with_items: php_packages
  notify: restart webserver
  sudo: true
