---
- name: Update apt cache (Debian).
  apt: update_cache=yes cache_valid_time=86400
  when: apt_update is not defined

- block:
    # set packages by version
    - name: Add Dotdeb packages key
      apt_key:
        url: "https://www.dotdeb.org/dotdeb.gpg"
        state: present
      when: php_version == 7


    - name: Add the dotdeb repos
      apt_repository:
        repo: "{{ item }}"
        state: present
        filename: "/etc/apt/sources.list.d/dotdeb.list"
        update_cache: yes
      with_items:
         - "deb http://packages.dotdeb.org jessie all"
         - "deb-src http://packages.dotdeb.org jessie all"

  when: php_version == 7 and ansible_distribution_release == 'jessie'


- name: Ensure PHP packages are installed (Debian).
  apt:
    name: "{{ item }}"
    state: "{{ php_packages_state }}"
    install_recommends: "{{ php_install_recommends }}"
  with_items: "{{ php_packages }}"
  register: php_package_install
  notify: restart webserver

- name: Delete APCu configuration file if this role will provide one.
  file:
    path: "{{ item }}/{{ php_apc_conf_filename }}"
    state: absent
  with_items: "{{ php_extension_conf_paths }}"
  when: php_enable_apc and php_package_install.changed
  notify: restart webserver

- name: Delete OpCache configuration file if this role will provide one.
  file:
    path: "{{ item }}/{{ php_opcache_conf_filename }}"
    state: absent
  with_items: "{{ php_extension_conf_paths }}"
  when: php_opcache_enable and php_package_install.changed
  notify: restart webserver
