---
- name: Update apt cache (Debian).
  apt: update_cache=yes cache_valid_time=86400
  when: apt_update is not defined


- block:
    - name: Add repository for PHP versions (Ubuntu).
      apt_repository: repo='ppa:ondrej/php'

    - name: Add repository for PHP 5 compatibility packages (Ubuntu).
      apt_repository: repo='ppa:ondrej/php5-compat'
      when:
        - php_version == "5.6"
        - ansible_distribution == "Ubuntu"
        - ansible_distribution_release != "bionic"
  when: ansible_distribution == "Ubuntu"


- block:
    # set packages by version
    - name: Add Dotdeb packages key
      apt_key:
        url: "https://www.dotdeb.org/dotdeb.gpg"
        state: present
      when: php_version >= 7


    - name: Add the dotdeb repos
      apt_repository:
        repo: "{{ item }}"
        state: present
        filename: "/etc/apt/sources.list.d/dotdeb.list"
        update_cache: yes
      with_items:
         - "deb http://packages.dotdeb.org jessie all"
         - "deb-src http://packages.dotdeb.org jessie all"

  when: php_version >= 7.0 and ansible_distribution_release == 'jessie'


# Debian-specific tasks.
- block:
    - name: Add dependencies for PHP versions (Debian).
      apt:
        name: "{{ item }}"
      with_items:
        - apt-transport-https
        - ca-certificates

    - name: Add Ondrej Sury's apt key (Debian).
      apt_key:
        url: https://packages.sury.org/php/apt.gpg
        state: present

    - name: Add Ondrej Sury's repo (Debian).
      apt_repository:
        repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
        state: present
      register: php_ondrej_debian_repo

    - name: Update apt caches after repo is added (Debian).
      apt: update_cache=yes
      when: php_ondrej_debian_repo.changed

  when: ansible_distribution == "Debian"



- name: Ensure PHP packages are installed (Debian).
  apt:
    name: "{{ item }}"
    state: "{{ php_packages_state }}"
    install_recommends: "{{ php_install_recommends }}"
  with_items: "{{ php_packages }}"
  register: php_package_install
  notify: restart webserver

- name: Delete APCu configuration file if this role will provide one.
  file:
    path: "{{ item }}/{{ php_apc_conf_filename }}"
    state: absent
  with_items: "{{ php_extension_conf_paths }}"
  when: php_enable_apc and php_package_install.changed
  notify: restart webserver


- name: Set the correct opcache filename (Ubuntu/Debian).
  set_fact:
    php_opcache_conf_filename: "10-opcache.ini"


- name: Delete OpCache configuration file if this role will provide one.
  file:
    path: "{{ item }}/{{ php_opcache_conf_filename }}"
    state: absent
  with_items: "{{ php_extension_conf_paths }}"
  when: php_opcache_enable and php_package_install.changed
  notify: restart webserver
